
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    app: ecommerce-app
  name: ecommerce-app-master-branch-build
  namespace: tcbd1de-tools
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ecommerce-app-master-branch
    labels:
      app: ecommerce-app
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ecommerce-app-master-branch-build
    labels:
      app: ecommerce-app
      name: ecommerce-app-build
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ecommerce-app-master-branch:latest
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "250m"
        memory: 500Mi
    source:
      contextDir: "client"
      git:
        ref: master
        uri: https://github.com/blueQcloud/mern-ecommerce.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
        env:
        - name: PORT
          value: "8080"
      type: Docker
    triggers:
    - type: ConfigChange